# Generated by Django 4.2.2 on 2023-09-29 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cateogry_name', models.CharField(max_length=50)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategory_name', models.CharField(max_length=50)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_short_description', models.TextField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_upload_date', models.DateField()),
                ('product_status', models.IntegerField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.categories')),
                ('product_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.sub_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Image', models.ImageField(upload_to='shop/images')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.products')),
            ],
        ),
    ]
