# Generated by Django 4.2.2 on 2023-10-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_product_images_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_heading', models.CharField(max_length=100)),
                ('slider_text', models.CharField(max_length=255)),
                ('slider_Image', models.ImageField(upload_to='shop/slider_images')),
                ('slider_priorty', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
