# Generated by Django 4.2.2 on 2023-10-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_bestselling_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
